Vagrant.configure("2") do |o|
    o.vm.box = "ubuntu"
    o.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box" 
    o.vm.network :private_network, ip: "192.168.55.55"
end
